import { CourseModel } from "./model";

const coursesData: CourseModel[] = [
  {
    id: 1,
    code: "SI0034",
    semester_id: 3,
    name: "Pemrograman Berbasis Web",
    sks: 3,
    class: "SI3A",
    capacity: 28,
    schedule: [
      {
        id: 1,
        day_id: 1,
        session_id: 1,
        room: "B603",
      },
      {
        id: 2,
        day_id: 2,
        session_id: 2,
        room: "B605",
      },
    ],
  },
  {
    id: 2,
    code: "SI0001",
    semester_id: 1,
    name: "Pemrograman Dasar",
    sks: 3,
    class: "SI1A",
    capacity: 30,
    schedule: [
      {
        id: 1,
        day_id: 1,
        session_id: 1,
        room: "B603",
      },
      {
        id: 2,
        day_id: 2,
        session_id: 2,
        room: "B605",
      },
    ],
  },
  {
    id: 3,
    code: "SI0001",
    semester_id: 1,
    name: "Pemrograman Dasar",
    sks: 3,
    class: "SI1B",
    capacity: 21,
    schedule: [
      {
        id: 1,
        day_id: 1,
        session_id: 1,
        room: "B603",
      },
      {
        id: 2,
        day_id: 2,
        session_id: 2,
        room: "B605",
      },
    ],
  },
  {
    id: 4,
    code: "SI0201",
    semester_id: 5,
    name: "Pemrograman Berbasis Mobile",
    sks: 3,
    class: "SI5A",
    capacity: 40,
    schedule: [
      {
        id: 1,
        day_id: 3,
        session_id: 3,
        room: "A301",
      },
      {
        id: 2,
        day_id: 4,
        session_id: 4,
        room: "B602",
      },
    ],
  },
  {
    id: 5,
    code: "SI0003",
    semester_id: 6,
    name: "Pemrograman Berbasis Desktop",
    sks: 3,
    class: "SI6A",
    capacity: 35,
    schedule: [
      {
        id: 1,
        day_id: 5,
        session_id: 5,
        room: "B608",
      },
      {
        id: 2,
        day_id: 6,
        session_id: 6,
        room: "A301",
      },
    ],
  },
  {
    id: 6,
    code: "SI9001",
    semester_id: 4,
    name: "Pemrograman Berbasis Enterprise",
    sks: 3,
    class: "SI4A",
    capacity: 30,
    schedule: [
      {
        id: 1,
        day_id: 5,
        session_id: 1,
        room: "B609",
      },
      {
        id: 2,
        day_id: 1,
        session_id: 5,
        room: "A601",
      },
    ],
  },
  {
    id: 7,
    code: "SI0056",
    semester_id: 2,
    name: "Pemrograman Berbasis Cloud",
    sks: 3,
    class: "SI2A",
    capacity: 25,
    schedule: [
      {
        id: 1,
        day_id: 2,
        session_id: 3,
        room: "A301",
      },
      {
        id: 2,
        day_id: 3,
        session_id: 3,
        room: "B604",
      },
    ],
  },
  {
    id: 8,
    code: "SI0001",
    semester_id: 1,
    name: "Pemrograman Dasar",
    sks: 3,
    class: "SI1C",
    capacity: 25,
    schedule: [
      {
        id: 1,
        day_id: 5,
        session_id: 2,
        room: "B603",
      },
      {
        id: 2,
        day_id: 3,
        session_id: 5,
        room: "B605",
      },
    ],
  },
  {
    id: 9,
    code: "SI0201",
    semester_id: 5,
    name: "Pemrograman Berbasis Mobile",
    sks: 3,
    class: "SI5B",
    capacity: 6,
    schedule: [
      {
        id: 1,
        day_id: 3,
        session_id: 3,
        room: "A302",
      },
      {
        id: 2,
        day_id: 4,
        session_id: 4,
        room: "B605",
      },
    ],
  },
  {
    id: 10,
    code: "SI0003",
    semester_id: 6,
    name: "Pemrograman Berbasis Desktop",
    sks: 3,
    class: "SI6B",
    capacity: 35,
    schedule: [
      {
        id: 1,
        day_id: 5,
        session_id: 5,
        room: "B608",
      },
      {
        id: 2,
        day_id: 6,
        session_id: 6,
        room: "A301",
      },
    ],
  },
  {
    id: 11,
    code: "SI9001",
    semester_id: 4,
    name: "Pemrograman Berbasis Enterprise",
    sks: 3,
    class: "SI4B",
    capacity: 30,
    schedule: [
      {
        id: 1,
        day_id: 2,
        session_id: 5,
        room: "B607",
      },
      {
        id: 2,
        day_id: 5,
        session_id: 1,
        room: "B604",
      },
    ],
  },
  {
    id: 12,
    code: "SI0056",
    semester_id: 2,
    name: "Pemrograman Berbasis Cloud",
    sks: 3,
    class: "SI2B",
    capacity: 25,
    schedule: [
      {
        id: 1,
        day_id: 2,
        session_id: 3,
        room: "A301",
      },
      {
        id: 2,
        day_id: 3,
        session_id: 3,
        room: "B604",
      },
    ],
  },
  {
    id: 13,
    code: "SI0001",
    semester_id: 1,
    name: "Pemrograman Dasar",
    sks: 3,
    class: "SI1D",
    capacity: 25,
    schedule: [
      {
        id: 1,
        day_id: 1,
        session_id: 1,
        room: "B603",
      },
      {
        id: 2,
        day_id: 2,
        session_id: 2,
        room: "B605",
      },
    ],
  },
  {
    id: 14,
    code: "U0002",
    semester_id: 1,
    name: "Pendidikan Pancasila (SI)",
    sks: 2,
    class: "SI1D",
    capacity: 39,
    schedule: [
      {
        id: 1,
        day_id: 2,
        session_id: 1,
        room: "B303",
      },
    ],
  },
  {
    id: 15,
    code: "RSI0001",
    semester_id: 4,
    name: "Komputasi Hijau",
    sks: 4,
    class: "SI4A",
    capacity: 30,
    schedule: [
      {
        id: 1,
        day_id: 3,
        session_id: 7,
        room: "B603",
      },
      {
        id: 2,
        day_id: 1,
        session_id: 2,
        room: "A301",
      },
    ],
  },
  {
    id: 16,
    code: "SI0201",
    semester_id: 5,
    name: "Pemrograman Berbasis Mobile",
    sks: 3,
    class: "SI5C",
    capacity: 40,
    schedule: [
      {
        id: 1,
        day_id: 3,
        session_id: 3,
        room: "A301",
      },
      {
        id: 2,
        day_id: 4,
        session_id: 4,
        room: "B602",
      },
    ],
  },
  {
    id: 17,
    code: "SI0003",
    semester_id: 6,
    name: "Pemrograman Berbasis Desktop",
    sks: 3,
    class: "SI6C",
    capacity: 35,
    schedule: [
      {
        id: 1,
        day_id: 5,
        session_id: 5,
        room: "B608",
      },
      {
        id: 2,
        day_id: 6,
        session_id: 6,
        room: "A301",
      },
    ],
  },
  {
    id: 18,
    code: "S1106",
    semester_id: 3,
    name: "Matematika Diskrit",
    sks: 4,
    class: "SI3A",
    capacity: 22,
    schedule: [
      {
        id: 1,
        day_id: 5,
        session_id: 5,
        room: "A305",
      },
      {
        id: 2,
        day_id: 6,
        session_id: 6,
        room: "A306",
      },
    ],
  },
  {
    id: 19,
    code: "SI9001",
    semester_id: 4,
    name: "Pemrograman Berbasis Enterprise",
    sks: 3,
    class: "SI4C",
    capacity: 30,
    schedule: [
      {
        id: 1,
        day_id: 4,
        session_id: 7,
        room: "B301",
      },
      {
        id: 2,
        day_id: 3,
        session_id: 3,
        room: "A302",
      },
    ],
  },
  {
    id: 20,
    code: "SI0088",
    semester_id: 5,
    name: "Pengembangan Aplikasi Web",
    sks: 3,
    class: "SI5A",
    capacity: 33,
    schedule: [
      {
        id: 1,
        day_id: 4,
        session_id: 6,
        room: "A301",
      },
      {
        id: 2,
        day_id: 2,
        session_id: 4,
        room: "B604",
      },
    ],
  },
  {
    id: 21,
    code: "SI0001",
    semester_id: 1,
    name: "Pemrograman Dasar",
    sks: 3,
    class: "SI1E",
    capacity: 25,
    schedule: [
      {
        id: 1,
        day_id: 1,
        session_id: 1,
        room: "B603",
      },
      {
        id: 2,
        day_id: 2,
        session_id: 2,
        room: "B605",
      },
    ],
  },
  {
    id: 22,
    code: "U0002",
    semester_id: 1,
    name: "Pendidikan Pancasila (SI)",
    sks: 2,
    class: "SI1E",
    capacity: 40,
    schedule: [
      {
        id: 1,
        day_id: 2,
        session_id: 3,
        room: "B305",
      },
    ],
  },
  {
    id: 23,
    code: "RSI0001",
    semester_id: 4,
    name: "Komputasi Hijau",
    sks: 4,
    class: "SI4B",
    capacity: 30,
    schedule: [
      {
        id: 1,
        day_id: 3,
        session_id: 7,
        room: "B603",
      },
      {
        id: 2,
        day_id: 1,
        session_id: 2,
        room: "A301",
      },
    ],
  },
  {
    id: 24,
    code: "SI0018",
    semester_id: 5,
    name: "Rekayasa Perangkat Lunak",
    sks: 4,
    class: "SI5A",
    capacity: 29,
    schedule: [
      {
        id: 1,
        day_id: 4,
        session_id: 6,
        room: "A301",
      },
      {
        id: 2,
        day_id: 2,
        session_id: 4,
        room: "B604",
      },
    ],
  },
  {
    id: 25,
    code: "SI0018",
    semester_id: 5,
    name: "Rekayasa Perangkat Lunak",
    sks: 4,
    class: "SI5B",
    capacity: 37,
    schedule: [
      {
        id: 1,
        day_id: 5,
        session_id: 4,
        room: "A303",
      },
      {
        id: 2,
        day_id: 3,
        session_id: 2,
        room: "B607",
      },
    ],
  },
  {
    id: 26,
    code: "SI0010",
    semester_id: 3,
    name: "	Paradigma Berorientasi Objek I",
    sks: 3,
    class: "SI3A",
    capacity: 34,
    schedule: [
      {
        id: 1,
        day_id: 3,
        session_id: 1,
        room: "B602",
      },
      {
        id: 2,
        day_id: 6,
        session_id: 1,
        room: "B605",
      },
    ],
  },
  {
    id: 27,
    code: "SI0018",
    semester_id: 5,
    name: "Rekayasa Perangkat Lunak",
    sks: 4,
    class: "SI5C",
    capacity: 20,
    schedule: [
      {
        id: 1,
        day_id: 4,
        session_id: 4,
        room: "A305",
      },
      {
        id: 2,
        day_id: 1,
        session_id: 3,
        room: "B602",
      },
    ],
  },
  {
    id: 28,
    code: "SI0010",
    semester_id: 3,
    name: "	Paradigma Berorientasi Objek I",
    sks: 3,
    class: "SI3B",
    capacity: 36,
    schedule: [
      {
        id: 1,
        day_id: 2,
        session_id: 2,
        room: "A301",
      },
      {
        id: 2,
        day_id: 5,
        session_id: 5,
        room: "B605",
      },
    ],
  },
  {
    id: 29,
    code: "SI0018",
    semester_id: 5,
    name: "Rekayasa Perangkat Lunak",
    sks: 4,
    class: "SI5F",
    capacity: 40,
    schedule: [
      {
        id: 1,
        day_id: 5,
        session_id: 4,
        room: "A303",
      },
      {
        id: 2,
        day_id: 3,
        session_id: 2,
        room: "B607",
      },
    ],
  },
  {
    id: 30,
    code: "SI0024",
    semester_id: 4,
    name: "Gudang Data",
    sks: 2,
    class: "SI4A",
    capacity: 26,
    schedule: [
      {
        id: 2,
        day_id: 5,
        session_id: 1,
        room: "A606",
      },
    ],
  },
  {
    id: 31,
    code: "SI0024",
    semester_id: 4,
    name: "Gudang Data",
    sks: 2,
    class: "SI4B",
    capacity: 33,
    schedule: [
      {
        id: 2,
        day_id: 3,
        session_id: 4,
        room: "A606",
      },
    ],
  },
];

export { coursesData };
